---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: javagoof
    tier: webapp
  name: javagoof
spec:
  replicas: 1
  selector:
    matchLabels:
      app: javagoof
      tier: webapp
  template:
    metadata:
      labels:
        app: javagoof
        tier: webapp
    spec:
      containers:
      - image: ericsmalling/java-goof:kubecon1
        imagePullPolicy: Always
        name: javagoof
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: javagoof
  name: javagoof
spec:
  type: LoadBalancer
  # sessionAffinity: ClientIP
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: javagoof
    tier: webapp
